spring:
 profiles:
  active: dev
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
   username: root
   password: root
 jpa:
   hibernate:
   ddl-auto: updaten
 show-sql: true
my:
 name: jiaql
 age: 18
 number : ${random.int}
 uuid : ${random.uuid}
 max : ${random.int(10)}
 value : ${random.value}
 greeting : hi,i'm ${my.name}